#!/bin/bash

sudo "Generating OVPN for $1..."
cp template.ovpn $1.ovpn
echo $(sudo cat /etc/openvpn/server.conf | grep proto) >> $1.ovpn
PORT="$(echo $(sudo cat /etc/openvpn/server.conf | grep port) | cut -d " " -f 2)"
echo "remote $(curl ipinfo.io/ip) $PORT" >> $1.ovpn
echo "<ca>" >> $1.ovpn
sudo cat /etc/openvpn/easy-rsa/pki/ca.crt >> $1.ovpn
echo "</ca>" >> $1.ovpn
echo "<cert>" >> $1.ovpn
sudo cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> $1.ovpn
echo "</cert>" >> $1.ovpn
echo "<key>" >> $1.ovpn
sudo cat /etc/openvpn/easy-rsa/pki/private/$1.key >> $1.ovpn
echo "</key>" >> $1.ovpn
echo "<tls-auth>" >> $1.ovpn
sudo cat /etc/openvpn/ta.key >> $1.ovpn
echo "</tls-auth>" >> $1.ovpn
